### DEMAND MODEL REFERENCES ###

tour_purposes = (
    {
        "name": "hw",
        "orig": "home",
        "dest": "work",
        "area": "metropolitan",
    },
    {
        "name": "hc",
        "orig": "home",
        "dest": "comprehensive_school",
        "area": "metropolitan",
    },
    {
        "name": "hu",
        "orig": "home",
        "dest": "tertiary_education",
        "area": "metropolitan",
    },
    {
        "name": "hs",
        "orig": "home",
        "dest": "shopping",
        "area": "metropolitan",
    },
    {
        "name": "ho",
        "orig": "home",
        "dest": "other",
        "area": "metropolitan",
    },
    {
        "name": "wo",
        "orig": "source",
        "dest": "other",
        "source": ("hw",),
        "area": "all",
    },
    {
        "name": "oo",
        "orig": "source",
        "dest": "other",
        "source": ("hc", "hu", "hs", "ho",),
        "area": "all",
    },
    {
        "name": "hoo",
        "orig": "home",
        "dest": "any",
        "sec_dest": "any",
        "source": ("hw", "hc", "hu", "hs", "ho", "wo", "oo",),
        "area": "metropolitan",
    },
    {
        "name": "hwp",
        "orig": "home",
        "dest": "work",
        "area": "peripheral",
    },
    {
        "name": "hop",
        "orig": "home",
        "dest": "other",
        "area": "peripheral",
    },
    {
        "name": "sop",
        "orig": "home",
        "dest": "source",
        "area": "peripheral",
    },
    {
        "name": "oop",
        "orig": "source",
        "dest": "other",
        "source": ("sop",),
        "area": "all",
    },
)
areas = {
    "cbd_capital": (100, 131),
    "capital_other": (1000, 1230),
    "other_metropolitan": (2000, 3055),
    "surrounding": (4000, 5700),
    "peripheral": (6000, 6806),
    "external": (7000, 7009),
}
municipalities = {
    "Tallinn": (100, 1230),
    "Harku_vald": (2000, 2119),
    "Jõelähtme_vald": (2200, 2285),
    "Keila_linn": (2300, 2315),
    "Kiili_vald": (2400, 2441),
    "Maardu_linn": (2500, 2535),
    "Rae_vald": (2600, 2710),
    "Saku_vald": (2800, 2874),
    "Viimsi_vald": (2900, 2971),
    "Saue_vald": (3000, 4162),
    "Anija_vald": (4200, 4309),
    "Kohila_vald": (4400, 4494),
    "Kose_vald": (4500, 4629),
    "Kuusalu_vald": (4700, 4859),
    "Lääne-Harju_vald": (4900, 5085),
    "Loksa_linn": (5100, 5105),
    "Raasiku_vald": (5300, 5360),
    "Rapla_vald": (5400, 5700),
    "Märjamaa_vald": (6000, 6006),
    "Haljala_vald": (6100, 6103),
    "Järva_vald": (6200, 6206),
    "Kadrina_vald": (6300, 6301),
    "Kehtna_vald": (6400, 6403),
    "Lääne-Nigula_vald": (6500, 6509),
    "Paide_linn": (6600, 6602),
    "Türi_vald": (6700, 6705),
    "Tapa_vald": (6800, 6806),
    "external": (7000, 7009),
}
